### PR TITLE
Automatically select the appropriate socket type based on permission …

### PR DESCRIPTION
**Pull request by mokeyish**
…detection

### CODE REVIEW

**Comment by mokeyish** [comment]
@kolapapa Hi, I've fix ping timeout when use `unpriviledged icmp` in linux. Everything works fine (test in windows,macos,linux) except `PingIdentifier`， The linux kernel will regenerate `PingIdentifier` when in `unpriviledged icmp`  mode.

https://github.com/kolapapa/surge-ping/issues/30#issuecomment-1314704664

**Comment by kolapapa** [comment]
> The linux kernel will regenerate PingIdentifier when in unpriviledged icmp mode.

Sorry for the late reply, I'll do a test first.

**Comment by kolapapa** [comment]
@mokeyish  Thank you very much for your PR, I have a question to discuss? 
What if the user wants to execute commands directly through a simple privileged user without doing some extra operations?

**Comment by mokeyish** [comment]
> What if the user wants to execute commands directly through a simple privileged user without doing some extra operations?

privileged user dosen't need to do extra opeations.

**Comment by kolapapa** [comment]
This `DGRAW` type will be automatically written into `id` and `seq` by the kernel (linux), and users cannot set it by themselves. If my system has set `net.ipv4.ping_group_range` as a normal range by default, resulting in `allow_unprivileged_icmp`, and cannot use the `id` and `seq` set by raw socket by default, I think this is not the best solution. Maybe we can use another way to let users choose.

For example:
```rust
// Users can decide to use `DGRAM` or `RAW` socket
// If you decide to use `DGRAM` socket, you need to pay attention that `id` and `seq` cannot be customized.
let config = Config::builder().unprivileged().build();
let client = Client::new(&config)?;

```

**Comment by mokeyish** [comment]
> This `DGRAW` type will be automatically written into `id` and `seq` by the kernel (linux), and users cannot set it by themselves. If my system has set `net.ipv4.ping_group_range` as a normal range by default, resulting in `allow_unprivileged_icmp`, and cannot use the `id` and `seq` set by raw socket by default, I think this is not the best solution. Maybe we can use another way to let users choose.
> 
> For example:
> 
> ```rust
> // Users can decide to use `DGRAM` or `RAW` socket
> // If you decide to use `DGRAM` socket, you need to pay attention that `id` and `seq` cannot be customized.
> let config = Config::builder().unprivileged().build();
> let client = Client::new(&config)?;
> ```

I don't think it's a good idea to allow users to manually set the socket type. on the contrary, we should make `seq` as `id`, and use unique `seq` to identify waiter. (`DGRAM` socket not always available)
https://github.com/kolapapa/surge-ping/blob/1a5ae14deadfdf8b064a15de7fde10c941971007/src/client.rs#L179-L180

图片


**The goal of this library is to test the response time of a target address, the user doesn't care about the socket type.**

**Comment by kolapapa** [comment]
> 



> > This `DGRAW` type will be automatically written into `id` and `seq` by the kernel (linux), and users cannot set it by themselves. If my system has set `net.ipv4.ping_group_range` as a normal range by default, resulting in `allow_unprivileged_icmp`, and cannot use the `id` and `seq` set by raw socket by default, I think this is not the best solution. Maybe we can use another way to let users choose.
> > For example:
> > ```rust
> > // Users can decide to use `DGRAM` or `RAW` socket
> > // If you decide to use `DGRAM` socket, you need to pay attention that `id` and `seq` cannot be customized.
> > let config = Config::builder().unprivileged().build();
> > let client = Client::new(&config)?;
> > ```
> 
> I don't think it's a good idea to allow users to manually set the socket type. on the contrary, we should make `seq` as `id`, and use unique `seq` to identify waker.
> 
> 图片
> 
> **The goal of this library is to test the response time of a target address, the user doesn't care about the socket type.**

In our usage scenario, we focus on `id` and `seq` information. We have ping detection requirements for a large number of addresses, `id` can help us filter information from dump files conveniently, and free setting of `seq` information can help us deal with special needs (freely control the growth and loop of `seq`).

Users should create sockets according to their own needs, and the program should not make automatic choices. This is also one of the differences from other crates similar to ICMP.

- Freedom to control packet information
- Socket multiplexing
- Personalized configuration socket

If users want to use non-privileged icmp, they should clearly know their own needs and be able to accept the intervention and modification behavior of the kernel. It is often not the best choice for the program to make its own judgment. It can be the default, but the user cannot be allowed to choose freely.

**Comment by mokeyish** [comment]
If surge-ping is compiled into a binary executable program, users cannot modify it, and it must be able to automatically adapt to the permissions of various operating systems. 😂

**Comment by mokeyish** [comment]
`seq` can also be used as id. is there a better way?

**Comment by kolapapa** [comment]
> If surge-ping is compiled into a binary executable program, users cannot modify it, and it must be able to automatically adapt to the permissions of various operating systems. 😂


I think this is a prompt that should improve the exception information to help users, or a detailed document introduction.

From my test of this PR, when I want to execute a program under the root user, I actually want to use a `RAW` socket, but because the system enables `ping_group_range` by default, `DGRAM` is automatically used.😥 

And I haven't done deep testing on other systems, don't know if `DGRAM` will perform effectively and correctly. 😅

**Comment by kolapapa** [comment]
> `seq` can also be used as id. is there a better way?

I don't understand what this means?


We have a lot of tests. In some cases, when `seq` starts from 0 and goes to N, the `echo_request` packet will be intercepted by some unknown reasons.  So when we wrote this crates, we made a decision: it must be possible to personalize these key information.

**Comment by mokeyish** [comment]
> From my test of this PR, when I want to execute a program under the root user, I actually want to use a `RAW` socket, but because the system enables `ping_group_range` by default, `DGRAM` is automatically used.😥

It can be modified to prefer `RAW` socket .

**Comment by mokeyish** [comment]
> > `seq` can also be used as id. is there a better way?
> 
> I don't understand what this means?

I mean generate unique `seq` by pinger, not let it go from 0 to N.

**Comment by kolapapa** [comment]
> I mean generate unique `seq` by pinger, not let it go from 0 to N.

This feels inconvenient for later analysis, and the order in which the packets arrive cannot be judged which one is returned.

**Comment by mokeyish** [comment]
> > I mean generate unique `seq` by pinger, not let it go from 0 to N.
> 
> This feels inconvenient for later analysis, and the order in which the packets arrive cannot be judged which one is returned.

Or add a mapping of seq internally.😂

---
1. In order to get correct `waiter`
https://github.com/kolapapa/surge-ping/blob/1a5ae14deadfdf8b064a15de7fde10c941971007/src/client.rs#L179-L180

2. I set `ident` to `0`. 
图片

https://github.com/mokeyish/surge-ping/blob/828fb2721760d1a55e954e703ba2bfa79d116ef5/src/ping.rs#L48-L50

3. But `seq` may be duplicated.

**Pull request closed without merging**
